#!/usr/bin/env bash
# Installs the whole local stack into the `hermes` namespace, in dependency order.
# Image tags come from tools/scripts/.image-tags, written by build-images.sh —
# run that script first (or pass --build here) whenever image code changes.
# Rebuilding on every install is unnecessary: build_image already tags by
# content ID, so nothing downstream needs re-running just to install again.
set -euo pipefail

NAMESPACE="${NAMESPACE:-hermes}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CHARTS_DIR="$REPO_ROOT/helm-charts"
TAGS_FILE="$REPO_ROOT/tools/scripts/.image-tags"

if [[ "${1:-}" == "--build" ]]; then
    "$REPO_ROOT/tools/scripts/build-images.sh"
    shift
fi

[[ -s "$TAGS_FILE" ]] || "$REPO_ROOT/tools/scripts/build-images.sh"

declare -A IMAGE_TAGS
while IFS=: read -r name tag; do
    [[ -n "$name" ]] || continue
    IMAGE_TAGS["$name"]="$tag"
done < "$TAGS_FILE"

CARGO_LEXICAL_TAG="${IMAGE_TAGS[cargo-lexical]}"
DEMO_PRODUCER_TAG="${IMAGE_TAGS[demo-producer]}"
INDEX_DEFINITIONS_TAG="${IMAGE_TAGS[index-definitions]}"

# Services that have a chart under services/, one release each below.
SERVICES=(candy-reports-lexical chat-messages-lexical chat-rooms-lexical chat-users-lexical chief-lexical)

echo "==> Resolving chart dependencies"

# `helm dependency update` re-resolves and re-downloads every subchart on
# every run. Chart.lock already pins them, so skip the fetch when each locked
# dependency is present under charts/. Timestamps are useless for this: a
# fresh clone stamps Chart.yaml and Chart.lock identically, so compare content.

# Number of entries under a `dependencies:` block.
count_deps() {
    awk '/^dependencies:/ { inblock = 1; next }
         /^[^ -]/         { inblock = 0 }
         inblock && /^[[:space:]]*-?[[:space:]]*name:/ { n++ }
         END              { print n + 0 }' "$1"
}

# True when every dependency in Chart.lock has its tarball on disk, and the
# lock still covers everything Chart.yaml declares.
deps_satisfied() {
    local dir="$1" line name="" version=""

    [[ -f "$dir/Chart.lock" ]] || return 1
    [[ "$(count_deps "$dir/Chart.yaml")" == "$(count_deps "$dir/Chart.lock")" ]] || return 1

    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%$'\r'}"
        case "$line" in
            *name:*)    name="${line#*name: }" ;;
            *version:*) version="${line#*version: }"
                        [[ -f "$dir/charts/$name-$version.tgz" ]] || return 1
                        name="" ;;
        esac
    done < "$dir/Chart.lock"
}

resolve_deps() {
    local dir="$1"

    grep -q '^dependencies:' "$dir/Chart.yaml" || return 0
    deps_satisfied "$dir" && return 0

    # A lock exists but is unsatisfied: honour its pins rather than re-resolving.
    if [[ -f "$dir/Chart.lock" ]]; then
        helm dependency build "$dir" >/dev/null
    else
        helm dependency update "$dir" >/dev/null
    fi
}

while IFS= read -r chart; do
    resolve_deps "$(dirname "$chart")"
done < <(find "$CHARTS_DIR" -name Chart.yaml)

kubectl get namespace "$NAMESPACE" >/dev/null 2>&1 || kubectl create namespace "$NAMESPACE"

install() {
    local release="$1" chart="$2"
    shift 2
    echo "==> $release"
    helm upgrade --install "$release" "$CHARTS_DIR/$chart" -n "$NAMESPACE" --timeout 15m "$@"
}

install kafka         local-infra/backing/kafka/kafka                --wait
install minio         local-infra/backing/minio                      --wait
install elasticsearch local-infra/backing/elastic/elasticsearch      --wait
install mongodb       local-infra/backing/mongodb/mongodb            --wait
install tika          local-infra/backing/tika                       --wait
install kafka-ui      local-infra/backing/kafka/kafka-ui             --wait
install kibana        local-infra/backing/elastic/kibana             --wait
install mongo-express local-infra/backing/mongodb/mongo-express      --wait
# chief-lexical enriches from this; see local-infra/backing/chief-api for what it stands in for.
install chief-api     local-infra/backing/chief-api                  --wait
install headlamp      local-infra/tooling/headlamp                   --wait
# Telemetry backends before the collector, which starts pushing as soon as it is up.
install mimir         local-infra/observability/mimir                --wait
install loki          local-infra/observability/loki                 --wait
install tempo         local-infra/observability/tempo                --wait
install grafana       local-infra/observability/grafana              --wait
install otel-operator local-infra/observability/otel-operator        --wait

# The operator's webhook serving cert is regenerated by helm on every upgrade,
# but nothing on the Deployment changes, so the running pod keeps serving the
# previous cert while the webhook configs already carry the new CA. Creating an
# OpenTelemetryCollector then fails the admission webhook with
# "x509: certificate signed by unknown authority". Restarting the operator makes
# it load the cert helm just wrote.
echo "==> Restarting otel-operator (reload regenerated webhook cert)"
kubectl -n "$NAMESPACE" rollout restart deploy/otel-operator
kubectl -n "$NAMESPACE" rollout status deploy/otel-operator --timeout=180s

# The webhook Service's endpoint can lag the pod's readiness by a few
# seconds — kube-proxy hasn't synced yet even though rollout status just
# reported Ready — so the very next admission call here occasionally times
# out with "context deadline exceeded". That failure is transient, but
# `helm upgrade --install` leaves the release stuck in state "failed" and
# set -e would otherwise abort before the jobs and consumers install at all.
for attempt in 1 2 3 4 5; do
    if install otel-collector local-infra/observability/otel-collector; then
        break
    fi
    [[ "$attempt" == 5 ]] && { echo "otel-collector install failed after 5 attempts" >&2; exit 1; }
    echo "    webhook not ready yet, retrying ($attempt/5)..."
    sleep 5
done

# Both jobs run before the consumers, which is also the order populate.sh keeps:
# the consumers' memory requests leave the single dev node with no room for a
# job pod to schedule into, and a consumer subscribed to a topic that does not
# exist yet dies on UNKNOWN_TOPIC_OR_PART — the topics are auto-created by the
# producer. Every service reads with auto.offset.reset=earliest, so starting
# after the produce still consumes the whole backlog.
#install index-definitions local-infra/tooling/index-definitions --set "image.tag=$INDEX_DEFINITIONS_TAG"
install demo-producer     local-infra/tooling/demo-producer     --set "image.tag=$DEMO_PRODUCER_TAG"
for service in "${SERVICES[@]}"; do
    install "$service" "services/$service" --set "image.tag=${IMAGE_TAGS[$service]}"
done
# Same cargo-lexical image, different topic/index — no image of their own to build.
install cargo-operational-lexical services/cargo-operational-lexical --set "image.tag=$CARGO_LEXICAL_TAG"
install cargo-my-storage-lexical  services/cargo-my-storage-lexical  --set "image.tag=$CARGO_LEXICAL_TAG"

echo
echo "Done. UI access: tools/scripts/port-forward.sh"
