#!/usr/bin/env bash
# Installs the whole local stack into the `hermes` namespace, in dependency order.
set -euo pipefail

NAMESPACE="${NAMESPACE:-hermes}"
CHARTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$CHARTS_DIR/.." && pwd)"

# A fresh tag per build: Kubernetes caches images by tag, so rebuilding
# :local would leave the old bits running.
IMAGE_TAG="${IMAGE_TAG:-dev-$(date +%Y%m%d%H%M%S)}"

# Every service that has both a chart under services/ and a consumer image.
SERVICES=(cargo-lexical chat-lexical chat-rooms-lexical chat-users-lexical chief-lexical)

echo "==> Building images ($IMAGE_TAG)"
for service in "${SERVICES[@]}"; do
    docker build -f "$REPO_ROOT/Dockerfile" --build-arg "SERVICE=$service" -t "$service:$IMAGE_TAG" "$REPO_ROOT"
done
docker build -t "demo-producer:$IMAGE_TAG" "$REPO_ROOT/demo-producer"

echo "==> Resolving chart dependencies"

# `helm dependency update` re-resolves and re-downloads every subchart on
# every run. Chart.lock already pins them, so skip the fetch when each locked
# dependency is present under charts/. Timestamps are useless for this: a
# fresh clone stamps Chart.yaml and Chart.lock identically, so compare content.

# Number of entries under a `dependencies:` block.
count_deps() {
    awk '/^dependencies:/ { inblock = 1; next }
         /^[^ -]/         { inblock = 0 }
         inblock && /^[[:space:]]*-?[[:space:]]*name:/ { n++ }
         END              { print n + 0 }' "$1"
}

# True when every dependency in Chart.lock has its tarball on disk, and the
# lock still covers everything Chart.yaml declares.
deps_satisfied() {
    local dir="$1" line name="" version=""

    [[ -f "$dir/Chart.lock" ]] || return 1
    [[ "$(count_deps "$dir/Chart.yaml")" == "$(count_deps "$dir/Chart.lock")" ]] || return 1

    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%$'\r'}"
        case "$line" in
            *name:*)    name="${line#*name: }" ;;
            *version:*) version="${line#*version: }"
                        [[ -f "$dir/charts/$name-$version.tgz" ]] || return 1
                        name="" ;;
        esac
    done < "$dir/Chart.lock"
}

resolve_deps() {
    local dir="$1"

    grep -q '^dependencies:' "$dir/Chart.yaml" || return 0
    deps_satisfied "$dir" && return 0

    # A lock exists but is unsatisfied: honour its pins rather than re-resolving.
    if [[ -f "$dir/Chart.lock" ]]; then
        helm dependency build "$dir" >/dev/null
    else
        helm dependency update "$dir" >/dev/null
    fi
}

while IFS= read -r chart; do
    resolve_deps "$(dirname "$chart")"
done < <(find "$CHARTS_DIR" -name Chart.yaml)

kubectl get namespace "$NAMESPACE" >/dev/null 2>&1 || kubectl create namespace "$NAMESPACE"

install() {
    local release="$1" chart="$2"
    shift 2
    echo "==> $release"
    helm upgrade --install "$release" "$CHARTS_DIR/$chart" -n "$NAMESPACE" --timeout 15m "$@"
}

install kafka         utils/infra/kafka/kafka                --wait
install minio         utils/infra/minio                      --wait
install elasticsearch utils/infra/elastic/elasticsearch      --wait
install mongodb       utils/infra/mongodb/mongodb            --wait
install tika          utils/infra/tika                       --wait
install kafka-ui      utils/infra/kafka/kafka-ui             --wait
install kibana        utils/infra/elastic/kibana             --wait
install mongo-express utils/infra/mongodb/mongo-express      --wait
install headlamp      utils/dev/headlamp                     --wait
# chief-lexical enriches from this; see utils/dev/chief-api for what it stands in for.
install chief-api     utils/dev/chief-api                    --wait
# Telemetry backends before the collector, which starts pushing as soon as it is up.
install mimir         utils/observability/mimir              --wait
install loki          utils/observability/loki               --wait
install tempo         utils/observability/tempo              --wait
install grafana       utils/observability/grafana            --wait
install otel-operator utils/observability/otel-operator      --wait

# The operator's webhook serving cert is regenerated by helm on every upgrade,
# but nothing on the Deployment changes, so the running pod keeps serving the
# previous cert while the webhook configs already carry the new CA. Creating an
# OpenTelemetryCollector then fails the admission webhook with
# "x509: certificate signed by unknown authority". Restarting the operator makes
# it load the cert helm just wrote.
echo "==> Restarting otel-operator (reload regenerated webhook cert)"
kubectl -n "$NAMESPACE" rollout restart deploy/otel-operator
kubectl -n "$NAMESPACE" rollout status deploy/otel-operator --timeout=180s

# The webhook Service's endpoint can lag the pod's readiness by a few
# seconds — kube-proxy hasn't synced yet even though rollout status just
# reported Ready — so the very next admission call here occasionally times
# out with "context deadline exceeded". That failure is transient, but
# `helm upgrade --install` leaves the release stuck in state "failed" and
# set -e would otherwise abort before the jobs and consumers install at all.
for attempt in 1 2 3 4 5; do
    if install otel-collector utils/observability/otel-collector; then
        break
    fi
    [[ "$attempt" == 5 ]] && { echo "otel-collector install failed after 5 attempts" >&2; exit 1; }
    echo "    webhook not ready yet, retrying ($attempt/5)..."
    sleep 5
done

# Both jobs run before the consumers, which is also the order populate.sh keeps:
# the consumers' memory requests leave the single dev node with no room for a
# job pod to schedule into, and a consumer subscribed to a topic that does not
# exist yet dies on UNKNOWN_TOPIC_OR_PART — the topics are auto-created by the
# producer. Every service reads with auto.offset.reset=earliest, so starting
# after the produce still consumes the whole backlog.
install es-index      utils/dev/es-index
install demo-producer utils/dev/demo-producer --set "image.tag=$IMAGE_TAG"
for service in "${SERVICES[@]}"; do
    install "$service" "services/$service" --set "image.tag=$IMAGE_TAG"
done

echo
echo "Done. UI access: helm-charts/scripts/port-forward.sh"
